/*********************************************************************
*                                                                    *
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                                                                    *
**********************************************************************
*                                                                    *
* C-file generated by:                                               *
*                                                                    *
*        GUI_Builder for emWin version 5.30                          *
*        Compiled Jul  1 2015, 10:50:32                              *
*        (c) 2015 Segger Microcontroller GmbH & Co. KG               *
*                                                                    *
**********************************************************************
*                                                                    *
*        Internet: www.segger.com  Support: support@segger.com       *
*                                                                    *
**********************************************************************
*/

// USER START (Optionally insert additional includes)
#include "stdint.h"
#include "jack_button_value.h"
#include "jack_emwin.h"
#include "ltk_debug.h"
// USER END

#include "DIALOG.h"

/*********************************************************************
*
*       Defines
*
**********************************************************************
*/


#define ID_WINDOW_0    CLOUD_PRINT_ID_WINDOW_0
#define ID_BUTTON_0    CLOUD_PRINT_ID_BUTTON_0 
#define ID_BUTTON_1    CLOUD_PRINT_ID_BUTTON_1 
#define ID_TEXT_0      CLOUD_PRINT_ID_TEXT_0
#define ID_TEXT_1      CLOUD_PRINT_ID_TEXT_1
#define ID_TEXT_2      CLOUD_PRINT_ID_TEXT_2


// USER START (Optionally insert additional defines)
// USER END

/*********************************************************************
*
*       Static data
*
**********************************************************************
*/

// USER START (Optionally insert additional static data)
// USER END

/*********************************************************************
*
*       _aDialogCreate
*/
static const GUI_WIDGET_CREATE_INFO _aDialogCreate[] = {
	{ WINDOW_CreateIndirect, "CloudPrint", ID_WINDOW_0, 0, 0, 320, 240, 0, 0x0, 0 },
	//{ BUTTON_CreateIndirect, "Pause", ID_BUTTON_0, 40, 181, 78, 36, 0, 0x0, 0 },
	{ BUTTON_CreateIndirect, "Stop",ID_BUTTON_1, 200, 150, 80, 60, 0, 0x0, 0 },
	{ TEXT_CreateIndirect, "Extuder", ID_TEXT_0, 50, 55, 100, 26, 0, 0x0, 0 },
	{ TEXT_CreateIndirect, "Bed",     ID_TEXT_1, 50, 85, 100, 26, 0, 0x0, 0 },
	{ TEXT_CreateIndirect, "Pos:", ID_TEXT_2, 20, 120, 280, 26, 0, 0x0, 0 },
	// USER START (Optionally insert additional widgets)
	// USER END
};

/*********************************************************************
*
*       Static code
*
**********************************************************************
*/

// USER START (Optionally insert additional static code)
// USER END

/*********************************************************************
*
*       _cbDialog
*/
extern float current_position[4] ;
static void _cbDialog(WM_MESSAGE * pMsg) {
	int NCode;
	int Id;
	// USER START (Optionally insert additional variables)
	WM_HWIN  hItem;
	char text_buffer[40]={0};
	int16_t temp = 0,temp1 = 0;
	// USER END

	switch (pMsg->MsgId) {
	case WM_INIT_DIALOG:
			
		/* 输出到挤出机温度显示 */
		hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_0);
		TEXT_SetFont(hItem,GUI_FONT_16B_ASCII);
		temp  = getTemperature(0); 
		temp1 = getTargetTemperature(0);  
		sprintf(text_buffer,"Extuder:%02d/%02d",temp,temp1);    
		TEXT_SetText(hItem,text_buffer);
	
		/* 输出到热床温度显示 */
		hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_1);
		TEXT_SetFont(hItem,GUI_FONT_16B_ASCII);
		temp  = getTemperature(1); 
		temp1 = getTargetTemperature(1);  
		sprintf(text_buffer,"HotBed:%02d/%02d",temp,temp1);    
		TEXT_SetText(hItem,text_buffer);
    
        /* 坐标显示输出 */
		hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_2);
		TEXT_SetFont(hItem,GUI_FONT_16B_ASCII);
		sprintf(text_buffer,"POS");    
		TEXT_SetText(hItem,text_buffer);      

case WM_PAINT:
    
        GUI_SetBkColor(BK_COLOR_2);
		GUI_SetColor(GUI_BLACK);
		GUI_Clear();
		GUI_SetFont(GUI_FONT_20B_ASCII);
		GUI_DispStringHCenterAt("CLOUD PRINT",160,25); 

		break;
			
	case WM_NOTIFY_PARENT:
		Id    = WM_GetId(pMsg->hWinSrc);
		NCode = pMsg->Data.v;
		switch(Id) {
		case ID_BUTTON_0: // Notifications sent by 'Pause'
			switch(NCode) {
			case WM_NOTIFICATION_CLICKED:
				// USER START (Optionally insert code for reacting on notification message)
				// USER END
				break;
			case WM_NOTIFICATION_RELEASED:
				// USER START (Optionally insert code for reacting on notification message)
				
				// USER END
				break;
			// USER START (Optionally insert additional code for further notification handling)
			// USER END
			}
			break;
		case ID_BUTTON_1: // Notifications sent by 'Stop'
			switch(NCode) {
			case WM_NOTIFICATION_CLICKED:
				// USER START (Optionally insert code for reacting on notification message)
				// USER END
				break;
			case WM_NOTIFICATION_RELEASED:
				// USER START (Optionally insert code for reacting on notification message)
                ltk_printf("stop: 0 \r\n");
                cloud_stop_print();
                //CloudWinDelete();
				// USER END
				break;
			// USER START (Optionally insert additional code for further notification handling)
			// USER END
			}
			break;
		// USER START (Optionally insert additional code for further Ids)
		// USER END
		}
		break;
	// USER START (Optionally insert additional message handling)
	// USER END
	case TEMPERATRUE_REPORT:  //处理温度显示信息，每秒修改一次
		/* 输出到挤出机温度显示 */
		hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_0);
		TEXT_SetFont(hItem,GUI_FONT_16B_ASCII);
		temp  = getTemperature(0); 
		temp1 = getTargetTemperature(0);  
		sprintf(text_buffer,"Extuder:%02d/%02d",temp,temp1);    
		TEXT_SetText(hItem,text_buffer);
	
		/* 输出到热床温度显示 */
		hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_1);
		TEXT_SetFont(hItem,GUI_FONT_16B_ASCII);
		temp  = getTemperature(1); 
		temp1 = getTargetTemperature(1);  
		sprintf(text_buffer,"HotBed:%02d/%02d",temp,temp1);    
		TEXT_SetText(hItem,text_buffer);
    
        /* 坐标显示输出 */
		hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_2);
		TEXT_SetFont(hItem,GUI_FONT_16B_ASCII);
		sprintf(text_buffer,"POS X:%6.3f/Y:%6.3f/Z:%6.3f",current_position[0],current_position[1],current_position[2]);    
		TEXT_SetText(hItem,text_buffer);    
        
		break;
	default:
		WM_DefaultProc(pMsg);
		break;
	}
}

/*********************************************************************
*
*       Public code
*
**********************************************************************
*/
/*********************************************************************
*
*       CreateCloudPrint
*/
WM_HWIN CreateCloudPrint(void);
WM_HWIN CreateCloudPrint(void) {
	WM_HWIN hWin;

	hWin = GUI_CreateDialogBox(_aDialogCreate, GUI_COUNTOF(_aDialogCreate), _cbDialog, WM_HBKWIN, 0, 0);
	return hWin;
}

// USER START (Optionally insert additional public code)
// USER END

/*************************** End of file ****************************/
