/*********************************************************************
*                                                                    *
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                                                                    *
**********************************************************************
*                                                                    *
* C-file generated by:                                               *
*                                                                    *
*        GUI_Builder for emWin version 5.30                          *
*        Compiled Jul  1 2015, 10:50:32                              *
*        (c) 2015 Segger Microcontroller GmbH & Co. KG               *
*                                                                    *
**********************************************************************
*                                                                    *
*        Internet: www.segger.com  Support: support@segger.com       *
*                                                                    *
**********************************************************************
*/

// USER START (Optionally insert additional includes)
#include "string.h"
#include "stm32f10x.h"
#include "jack_button_value.h"
#include "user_sd.h"
#include "jack_emwin.h"
// USER END

#include "DIALOG.h"


/*********************************************************************
*
*       Defines
*
**********************************************************************
*/
#define ID_FRAMEWIN_1    FILE_PRINT_TRUE_ID_FRAMEWIN_1
#define ID_BUTTON_2      FILE_PRINT_TRUE_ID_BUTTON_2
#define ID_BUTTON_3      FILE_PRINT_TRUE_ID_BUTTON_3
#define ID_TEXT_1        FILE_PRINT_TRUE_ID_TEXT_1 

// USER START (Optionally insert additional defines)
// USER END

/*********************************************************************
*
*       Static data
*
**********************************************************************
*/

// USER START (Optionally insert additional static data)
// USER END

/*********************************************************************
*
*       _aDialogCreate
*/
static const GUI_WIDGET_CREATE_INFO _aDialogCreate[] = {
	{ FRAMEWIN_CreateIndirect, "PrintFileWaring", ID_FRAMEWIN_1, 60, 60, 200, 120, 0, 0x0, 0 },
	{ BUTTON_CreateIndirect, "YES", ID_BUTTON_2, 15, 50, 52, 30, 0, 0x0, 0 },
	{ BUTTON_CreateIndirect, "NO", ID_BUTTON_3, 105, 50, 52, 30, 0, 0x0, 0 },
	{ TEXT_CreateIndirect, "Printf this file", ID_TEXT_1, 5, 20, 180, 32, 0, 0x0, 0 },
	//{ TEXT_CreateIndirect, "Printf this file", ID_TEXT_1, 20, 18, 140, 32, 0, 0x0, 0 },
	// USER START (Optionally insert additional widgets)
	// USER END
};

/*********************************************************************
*
*       Static code
*
**********************************************************************
*/

// USER START (Optionally insert additional static code)
// USER END

/*********************************************************************
*
*       _cbDialog
*/
extern __IO uint64_t print_start_time;
extern __IO uint64_t print_current_time;
extern __IO uint64_t print_used_time;
extern WM_HWIN hDialog;
extern char curentopenfile[];
static void _cbDialog(WM_MESSAGE * pMsg) {
	int NCode;
	int Id;
	// USER START (Optionally insert additional variables)
	WM_HWIN hWin = pMsg->hWin;
	WM_HWIN hItem;
	// USER END

	switch (pMsg->MsgId) { 
	case WM_INIT_DIALOG:

        //_HideFrame();  
        WM_DisableWindow(hDialog);
        WM_SetFocus(hWin);
        
        FRAMEWIN_AddCloseButton(hWin, FRAMEWIN_BUTTON_RIGHT, 0);  //初始的对话框就是当前的，直接操作就可以了
        FRAMEWIN_SetTitleHeight(hWin,20);
        FRAMEWIN_SetFont(hWin,&GUI_Font16B_ASCII);
        
        hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_1);
        TEXT_SetTextAlign(hItem,TEXT_CF_HCENTER);
        TEXT_SetFont(hItem,&GUI_FontHZ16);
        TEXT_SetText(hItem,curentopenfile);
        break; 
	
	case WM_NOTIFY_PARENT:
		Id    = WM_GetId(pMsg->hWinSrc);
		NCode = pMsg->Data.v;
		switch(Id) {
		case ID_BUTTON_2: // Notifications sent by 'YES'
			switch(NCode) {
			case WM_NOTIFICATION_CLICKED:
				// USER START (Optionally insert code for reacting on notification message)
				// USER END
				break;
			case WM_NOTIFICATION_RELEASED:
				// USER START (Optionally insert code for reacting on notification message)
				//设置打印该文件
				#if _USE_LFN
                memset(Fs_LongFileName,0,sizeof(Fs_LongFileName));
				memcpy(Fs_LongFileName,curentopenfile,strlen(curentopenfile));
				c_sdReader_open(Fs_LongFileName);
				#else
                memset(Fs_FileName,0,sizeof(Fs_FileName));
				memcpy(Fs_FileName,curentopenfile,strlen(curentopenfile));
				c_sdReader_open(Fs_FileName);
				#endif
				sd_print_start();
				//记录开始时间
				print_start_time = GUI_GetTime(); 
				print_current_time = 0;
				print_used_time = 0;
				
				WM_DeleteWindow(hDialog);
				_CreateFrame(&_cbPrinting);
				GUI_EndDialog(hWin, 0);
				// USER END
				break;
			// USER START (Optionally insert additional code for further notification handling)
			// USER END
			}
			break;
			
		case ID_BUTTON_3: // Notifications sent by 'NO'
			switch(NCode) {
			case WM_NOTIFICATION_CLICKED:
				// USER START (Optionally insert code for reacting on notification message)
				// USER END
				break;
			case WM_NOTIFICATION_RELEASED:
				// USER START (Optionally insert code for reacting on notification message)
				GUI_EndDialog(hWin, 0);
				// USER END
				break;
			// USER START (Optionally insert additional code for further notification handling)
			// USER END
			}
			break;
		// USER START (Optionally insert additional code for further Ids)
		// USER END
		}
		break;
	// USER START (Optionally insert additional message handling)
	// USER END
	default:
		WM_DefaultProc(pMsg);
		break;
	}
}

/*********************************************************************
*
*       Public code
*
**********************************************************************
*/
/*********************************************************************
*
*       CreatePrintFileWaring
*/
WM_HWIN CreatePrintFileWaring(void);
WM_HWIN CreatePrintFileWaring(void) {
	WM_HWIN hWin;

	hWin = GUI_CreateDialogBox(_aDialogCreate, GUI_COUNTOF(_aDialogCreate), _cbDialog, WM_HBKWIN, 0, 0);
	return hWin;
}

// USER START (Optionally insert additional public code)
// USER END

/*************************** End of file ****************************/
