/*********************************************************************
*                                                                    *
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                                                                    *
**********************************************************************
*                                                                    *
* C-file generated by:                                               *
*                                                                    *
*        GUI_Builder for emWin version 5.30                          *
*        Compiled Jul  1 2015, 10:50:32                              *
*        (c) 2015 Segger Microcontroller GmbH & Co. KG               *
*                                                                    *
**********************************************************************
*                                                                    *
*        Internet: www.segger.com  Support: support@segger.com       *
*                                                                    *
**********************************************************************
*/

// USER START (Optionally insert additional includes)
#include "marlin.h"
#include "stdbool.h"
#include "stm32f10x.h"
#include "jack_emwin.h"
#include "jack_button_value.h"
// USER END

#include "DIALOG.h"

/*********************************************************************
*
*       Defines
*
**********************************************************************
*/
#define ID_FRAMEWIN_2    FILE_PRINT_STOP_ID_FRAMEWIN_2
#define ID_TEXT_2        FILE_PRINT_STOP_ID_TEXT_2
#define ID_BUTTON_4      FILE_PRINT_STOP_ID_BUTTON_4
#define ID_BUTTON_5      FILE_PRINT_STOP_ID_BUTTON_5


// USER START (Optionally insert additional defines)
// USER END

/*********************************************************************
*
*       Static data
*
**********************************************************************
*/

// USER START (Optionally insert additional static data)
// USER END

/*********************************************************************
*
*       _aDialogCreate
*/
static const GUI_WIDGET_CREATE_INFO _aDialogCreate[] = {
  { FRAMEWIN_CreateIndirect, "StopWarning", ID_FRAMEWIN_2, 60, 60, 200, 120, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "Sure to stop!!!", ID_TEXT_2, 24, 17, 142, 19, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "YES", ID_BUTTON_4, 22, 51, 60, 30, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "NO", ID_BUTTON_5, 112, 53, 60, 30, 0, 0x0, 0 },
  // USER START (Optionally insert additional widgets)
  // USER END
};

/*********************************************************************
*
*       Static code
*
**********************************************************************
*/

// USER START (Optionally insert additional static code)
// USER END

/*********************************************************************
*
*       _cbDialog
*/
extern bool print_status;
extern uint8_t bPrintPause;
bool stop_flag = false;
static void _cbDialog(WM_MESSAGE * pMsg) {
  int NCode;
  int Id;
  // USER START (Optionally insert additional variables)
  char temp_buf[30]={0};
  WM_HWIN hWin = pMsg->hWin;
  WM_HWIN hItem;
  // USER END

  switch (pMsg->MsgId) {
  case WM_INIT_DIALOG:
  FRAMEWIN_AddCloseButton(hWin, FRAMEWIN_BUTTON_RIGHT, 0);  //初始的对话框就是当前的，直接操作就可以了
  FRAMEWIN_SetTitleHeight(hWin,20);
  FRAMEWIN_SetFont(hWin,&GUI_Font16B_ASCII);
  
  hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_2);
  TEXT_SetTextAlign(hItem,TEXT_CF_HCENTER);
  TEXT_SetFont(hItem,GUI_FONT_16B_ASCII);
      
  case WM_NOTIFY_PARENT:
    Id    = WM_GetId(pMsg->hWinSrc);
    NCode = pMsg->Data.v;
    switch(Id) {
    case ID_BUTTON_4: // Notifications sent by 'YES'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        GUI_EndDialog(hWin, 0);
        //enquecommand("M403\r\n");
        sdcard_stop_print();
      #if 0
        _DeleteFrame(); 
        Jack_Stop(); 
        sdPrintFinish(1);  
        quickStop(); 
        code_flush();
        print_status =  false ;
        stop_flag = true;
        bPrintPause = 1;
        buflen = 1;
      
        plan_set_position(0, 0, 0, 0);
        sprintf(temp_buf,"G0 Z%6f F1200\n",current_position[Z_AXIS]+10);
        enquecommand(temp_buf);
        enquecommand("G28\n");
        //_CreateFrame(&_cbFileScan);	
        //CreateFileBrower(); 
        _CreateFrame(&_cbIndex); 
      #endif
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_BUTTON_5: // Notifications sent by 'NO'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        GUI_EndDialog(hWin, 0);
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    // USER START (Optionally insert additional code for further Ids)
    // USER END
    }
    break;
  // USER START (Optionally insert additional message handling)
  // USER END
  default:
    WM_DefaultProc(pMsg);
    break;
  }
}

/*********************************************************************
*
*       Public code
*
**********************************************************************
*/
/*********************************************************************
*
*       CreateStopWarning
*/
WM_HWIN CreateStopWarning(void);
WM_HWIN CreateStopWarning(void) {
  WM_HWIN hWin;

  hWin = GUI_CreateDialogBox(_aDialogCreate, GUI_COUNTOF(_aDialogCreate), _cbDialog, WM_HBKWIN, 0, 0);
  return hWin;
}

// USER START (Optionally insert additional public code)
// USER END

/*************************** End of file ****************************/
