/*********************************************************************
*                                                                    *
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                                                                    *
**********************************************************************
*                                                                    *
* C-file generated by:                                               *
*                                                                    *
*        GUI_Builder for emWin version 5.30                          *
*        Compiled Jul  1 2015, 10:50:32                              *
*        (c) 2015 Segger Microcontroller GmbH & Co. KG               *
*                                                                    *
**********************************************************************
*                                                                    *
*        Internet: www.segger.com  Support: support@segger.com       *
*                                                                    *
**********************************************************************
*/

// USER START (Optionally insert additional includes)
// USER END

#include "DIALOG.h"
#include "jack_button_value.h"
/*********************************************************************
*
*       Defines
*
**********************************************************************
*/
#define ID_FRAMEWIN_0    SYS_SET_DEAULLT_ID_FRAMEWIN_0
#define ID_BUTTON_0      SYS_SET_DEAULLT_ID_BUTTON_0
#define ID_BUTTON_1      SYS_SET_DEAULLT_ID_BUTTON_1
#define ID_TEXT_0        SYS_SET_DEAULLT_ID_TEXT_0

// USER START (Optionally insert additional defines)
extern void Config_ResetDefault(void);
extern WM_HWIN    _hLastFrame;
// USER END

/*********************************************************************
*
*       Static data
*
**********************************************************************
*/

// USER START (Optionally insert additional static data)
// USER END

/*********************************************************************
*
*       _aDialogCreate
*/
static const GUI_WIDGET_CREATE_INFO _aDialogCreate[] = {
	{ FRAMEWIN_CreateIndirect, "SetDefaultWaring", ID_FRAMEWIN_0, 60, 60, 200, 120, 0, 0x0, 0 },
	{ BUTTON_CreateIndirect, "YES", ID_BUTTON_0, 15, 50, 52, 30, 0, 0x0, 0 },
	{ BUTTON_CreateIndirect, "NO", ID_BUTTON_1, 105, 50, 52, 30, 0, 0x0, 0 },
	{ TEXT_CreateIndirect, "Set default!!!", ID_TEXT_0, 5, 20, 180, 32, 0, 0x0, 0 },
	// USER START (Optionally insert additional widgets)
	// USER END
};

/*********************************************************************
*
*       Static code
*
**********************************************************************
*/

// USER START (Optionally insert additional static code)
// USER END

/*********************************************************************
*
*       _cbDialog
*/
static void _cbDialog(WM_MESSAGE * pMsg) {
	int NCode;
	int Id;
	int i;
	// USER START (Optionally insert additional variables)
	WM_HWIN hWin = pMsg->hWin;
	WM_HWIN hItem;
	// USER END

	switch (pMsg->MsgId) {   
	case WM_INIT_DIALOG: 
		for (i = 0; i < 6; i++) {
				hItem = WM_GetDialogItem(_hLastFrame, SYS_BUTTON_INFO + i);
				WM_DisableWindow(hItem);
		}
		FRAMEWIN_AddCloseButton(hWin, FRAMEWIN_BUTTON_RIGHT, 0);  //初始的对话框就是当前的，直接操作就可以了
		FRAMEWIN_SetTitleHeight(hWin,20);
		FRAMEWIN_SetFont(hWin,&GUI_Font16B_ASCII); 
		
		hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_0);
		TEXT_SetTextAlign(hItem,TEXT_CF_HCENTER);
		TEXT_SetFont(hItem,GUI_FONT_16B_ASCII);
		
		break;
	case WM_NOTIFY_PARENT:
		Id    = WM_GetId(pMsg->hWinSrc);
		NCode = pMsg->Data.v;
		switch(Id) {
		case ID_BUTTON_0: // Notifications sent by 'YES'
			switch(NCode) {
			case WM_NOTIFICATION_CLICKED:
				// USER START (Optionally insert code for reacting on notification message)
				// USER END
				break;
			case WM_NOTIFICATION_RELEASED:
				// USER START (Optionally insert code for reacting on notification message)
				for (i = 0; i < 6; i++) {
						hItem = WM_GetDialogItem(_hLastFrame, SYS_BUTTON_INFO + i);
						WM_EnableWindow(hItem);
				}
				Config_ResetDefault();
				GUI_EndDialog(hWin, 0);
				// USER END
				break;
			// USER START (Optionally insert additional code for further notification handling)
			// USER END
			}
			break;
		case ID_BUTTON_1: // Notifications sent by 'NO'
			switch(NCode) {
			case WM_NOTIFICATION_CLICKED:
				// USER START (Optionally insert code for reacting on notification message)
				// USER END
				break;
			case WM_NOTIFICATION_RELEASED:
				// USER START (Optionally insert code for reacting on notification message)
				for (i = 0; i < 6; i++) {
						hItem = WM_GetDialogItem(_hLastFrame, SYS_BUTTON_INFO + i);
						WM_EnableWindow(hItem);
				} 
				GUI_EndDialog(hWin, 0);
				// USER END
				break;
			// USER START (Optionally insert additional code for further notification handling)
			// USER END
			}
			break;
		// USER START (Optionally insert additional code for further Ids)
		// USER END
		}
		break;
	// USER START (Optionally insert additional message handling)
	case WM_DELETE:  //当对话框删除时，需要将按键小工具激活
	{
		for (i = 0; i < 6; i++) {
				hItem = WM_GetDialogItem(_hLastFrame, SYS_BUTTON_INFO + i);
				WM_EnableWindow(hItem);
		}       
	}
	// USER END
	default:
		WM_DefaultProc(pMsg);
		break;
	}
}

/*********************************************************************
*
*       Public code
*
**********************************************************************
*/
/*********************************************************************
*
*       CreateSetDefaultWaring
*/
WM_HWIN CreateSetDefaultWaring(void);
WM_HWIN CreateSetDefaultWaring(void) {
	WM_HWIN hWin;

	hWin = GUI_CreateDialogBox(_aDialogCreate, GUI_COUNTOF(_aDialogCreate), _cbDialog, WM_HBKWIN, 0, 0);
	return hWin;
}

// USER START (Optionally insert additional public code)
// USER END

/*************************** End of file ****************************/
