/*********************************************************************
*                                                                    *
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                                                                    *
**********************************************************************
*                                                                    *
* C-file generated by:                                               *
*                                                                    *
*        GUI_Builder for emWin version 5.30                          *
*        Compiled Jul  1 2015, 10:50:32                              *
*        (c) 2015 Segger Microcontroller GmbH & Co. KG               *
*                                                                    *
**********************************************************************
*                                                                    *
*        Internet: www.segger.com  Support: support@segger.com       *
*                                                                    *
**********************************************************************
*/

// USER START (Optionally insert additional includes)
#include "jack_emwin.h"
#include "jack_button_value.h"
// USER END

#include "DIALOG.h"

/*********************************************************************
*
*       Defines
*
**********************************************************************
*/


#define ID_IMAGE_0_IMAGE_0    0x00
#define ID_IMAGE_0_IMAGE_1    0x01
// USER START (Optionally insert additional defines)
// USER END

/*********************************************************************
*
*       Static data
*
**********************************************************************
*/


// USER START (Optionally insert additional static data)
extern GUI_CONST_STORAGE GUI_BITMAP bmwifi_status_init;
extern GUI_CONST_STORAGE GUI_BITMAP bmwifi_status_disconnect;
extern GUI_CONST_STORAGE GUI_BITMAP bmwifi_status_connect;
extern GUI_CONST_STORAGE GUI_BITMAP bmwifi_status_timeout;

extern GUI_CONST_STORAGE GUI_BITMAP bmserver_connect;
extern GUI_CONST_STORAGE GUI_BITMAP bmserver_disconnect;
extern GUI_CONST_STORAGE GUI_BITMAP bmserver_init;
// USER END

/*********************************************************************
*
*       _aDialogCreate
*/
static const GUI_WIDGET_CREATE_INFO _aDialogCreate[] = {
	{ WINDOW_CreateIndirect, "Window", ROUTER_ID_WINDOW_0, 0, 0, 320, 20, 0, 0x0, 0 },
	{ TEXT_CreateIndirect,  "Jackey", ROUTER_ID_TEXT_0, 0, 0, 100, 20, 0, 0x0, 0 },
	{ IMAGE_CreateIndirect, "CloudImage", ROUTER_ID_IMAGE_0, 200, 0, 29, 21, 0, 0, 0 },
	{ IMAGE_CreateIndirect, "WifiImage", ROUTER_ID_IMAGE_1, 300, 0, 29, 21, 0, 0, 0 },
	// USER START (Optionally insert additional widgets)
	// USER END
};

/*********************************************************************
*
*       Static code
*
**********************************************************************
*/
// USER START (Optionally insert additional static code)
extern CONNECT_STATUS wifi_connect_status;
// USER END
#if 0
/*********************************************************************
*
*       _GetImage
*/
GUI_CONST_STORAGE GUI_BITMAP *bmwifi_status;
GUI_CONST_STORAGE GUI_BITMAP *bmserver_status;
GUI_BITMAP  _GetImage()
{
	switch(wifi_connect_status)
	{
		case connect_init:{
            bmwifi_status = &bmwifi_status_init;
            bmserver_status = NULL;
        } break;
        case connect_disconnect:{
            bmwifi_status = &bmwifi_status_disconnect;
            bmserver_status = NULL;
        } break;  
        case connect_right:{
            bmwifi_status = &bmwifi_status_connect;
            bmserver_status = &bmserver_disconnect;
        }break;
        case  connect_server:{
            bmwifi_status = &bmwifi_status_connect;
            bmserver_status = &bmserver_connect;
        }break; 
        case connect_timeout:{
            bmwifi_status = &bmwifi_status_connect;
            bmserver_status = &bmserver_disconnect;
        } break;             
        case connect_erro:{
            bmwifi_status =  &bmwifi_status_disconnect; 
            bmserver_status = &bmserver_disconnect;
        } break;
    }
}
#endif

/*********************************************************************
*
*       _cbDialog
*/

static void _cbDialog(WM_MESSAGE * pMsg) {
	const void * pData;
	WM_HWIN      hItem;
	U32          FileSize;
	// USER START (Optionally insert additional variables)
	// USER END

	switch (pMsg->MsgId) {
	case WM_INIT_DIALOG:
		//
		// Initialization of 'Image'
		//
        // USER START
        #if 1
		hItem = WM_GetDialogItem(pMsg->hWin, ROUTER_ID_IMAGE_1);
		switch(wifi_connect_status)
		{
			case connect_init:{
                IMAGE_SetBitmap(hItem, &bmwifi_status_init);
                hItem = WM_GetDialogItem(pMsg->hWin, ROUTER_ID_IMAGE_0);
                IMAGE_SetBitmap(hItem, &bmserver_init);      
            } break;
            case connect_disconnect:{
                IMAGE_SetBitmap(hItem, &bmwifi_status_disconnect);
                hItem = WM_GetDialogItem(pMsg->hWin, ROUTER_ID_IMAGE_0);
                IMAGE_SetBitmap(hItem, &bmserver_init);  
            } break;  
            case connect_right:{
                IMAGE_SetBitmap(hItem, &bmwifi_status_connect);
                hItem = WM_GetDialogItem(pMsg->hWin, ROUTER_ID_IMAGE_0);
                IMAGE_SetBitmap(hItem, &bmserver_disconnect);           
            }break;
            case  connect_server:{
                IMAGE_SetBitmap(hItem, &bmwifi_status_connect);
                hItem = WM_GetDialogItem(pMsg->hWin, ROUTER_ID_IMAGE_0);
                IMAGE_SetBitmap(hItem, &bmserver_connect);        
            }break; 
            case connect_timeout:{
                IMAGE_SetBitmap(hItem, &bmwifi_status_connect);
                hItem = WM_GetDialogItem(pMsg->hWin, ROUTER_ID_IMAGE_0);
                IMAGE_SetBitmap(hItem, &bmserver_disconnect);           
            } break;             
            case connect_erro:{
                IMAGE_SetBitmap(hItem, &bmwifi_status_disconnect); 
                hItem = WM_GetDialogItem(pMsg->hWin, ROUTER_ID_IMAGE_0);
                IMAGE_SetBitmap(hItem, &bmserver_disconnect);            
            } break;
        }
        #else
        hItem = WM_GetDialogItem(pMsg->hWin, ROUTER_ID_IMAGE_0);
        IMAGE_SetBitmap(hItem, &bmserver_disconnect);
        hItem = WM_GetDialogItem(pMsg->hWin, ROUTER_ID_IMAGE_1);
        IMAGE_SetBitmap(hItem, &bmwifi_status_init);            
        #endif
        // USER END  
		break;
    case WM_PAINT:
        GUI_SetBkColor(GUI_LIGHTGRAY);
        GUI_Clear();
        break;
#if 1
	case WIFI_STATUS_REPORT:  //wifi 状态上传
        // USER START
        
		hItem = WM_GetDialogItem(pMsg->hWin, ROUTER_ID_IMAGE_1);
		switch(wifi_connect_status)
		{
			case connect_init:{
                IMAGE_SetBitmap(hItem, &bmwifi_status_init);
                hItem = WM_GetDialogItem(pMsg->hWin, ROUTER_ID_IMAGE_0);
                IMAGE_SetBitmap(hItem, &bmserver_init);      
            } break;
            case connect_disconnect:{
                IMAGE_SetBitmap(hItem, &bmwifi_status_disconnect);
                hItem = WM_GetDialogItem(pMsg->hWin, ROUTER_ID_IMAGE_0);
                IMAGE_SetBitmap(hItem, &bmserver_init);  
            } break;  
            case connect_right:{
                IMAGE_SetBitmap(hItem, &bmwifi_status_connect);
                hItem = WM_GetDialogItem(pMsg->hWin, ROUTER_ID_IMAGE_0);
                IMAGE_SetBitmap(hItem, &bmserver_disconnect);           
            }break;
            case  connect_server:{
                IMAGE_SetBitmap(hItem, &bmwifi_status_connect);
                hItem = WM_GetDialogItem(pMsg->hWin, ROUTER_ID_IMAGE_0);
                IMAGE_SetBitmap(hItem, &bmserver_connect);        
            }break; 
            case connect_timeout:{
                IMAGE_SetBitmap(hItem, &bmwifi_status_connect);
                hItem = WM_GetDialogItem(pMsg->hWin, ROUTER_ID_IMAGE_0);
                IMAGE_SetBitmap(hItem, &bmserver_disconnect);           
            } break;             
            case connect_erro:{
                IMAGE_SetBitmap(hItem, &bmwifi_status_disconnect); 
                hItem = WM_GetDialogItem(pMsg->hWin, ROUTER_ID_IMAGE_0);
                IMAGE_SetBitmap(hItem, &bmserver_disconnect);            
            } break;
        }
	break;              
#endif  
	// USER END
	default:
		WM_DefaultProc(pMsg);
		break;
	}
}

/*********************************************************************
*
*       Public code
*
**********************************************************************
*/
/*********************************************************************
*
*       CreateWindow
*/
extern WM_HWIN _hLastFrame;
WM_HWIN CreateConnectWindow(void);
WM_HWIN CreateConnectWindow(void) {
	WM_HWIN hWin;

	hWin = GUI_CreateDialogBox(_aDialogCreate, GUI_COUNTOF(_aDialogCreate), _cbDialog, _hLastFrame, 0, 0);
	return hWin;
}

// USER START (Optionally insert additional public code)
// USER END

/*************************** End of file ****************************/
