/*********************************************************************
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                           www.segger.com                           *
**********************************************************************
*                                                                    *
* C-file generated by                                                *
*                                                                    *
*        Bitmap Converter for emWin V5.30.                           *
*        Compiled Jul  1 2015, 10:49:26                              *
*                                                                    *
*        (c) 1998 - 2015 Segger Microcontroller GmbH & Co. KG        *
*                                                                    *
**********************************************************************
*                                                                    *
* Source file: flolder_name                                          *
* Dimensions:  25 * 25                                               *
* NumColors:   3                                                     *
*                                                                    *
**********************************************************************
*/

#include <stdlib.h>

#include "GUI.h"

#ifndef GUI_CONST_STORAGE
  #define GUI_CONST_STORAGE const
#endif

extern GUI_CONST_STORAGE GUI_BITMAP bmflolder_name;

/*********************************************************************
*
*       Palette
*
*  Description
*    The following are the entries of the palette table.
*    The entries are stored as a 32-bit values of which 24 bits are
*    actually used according to the following bit mask: 0xBBGGRR
*
*    The lower   8 bits represent the Red   component.
*    The middle  8 bits represent the Green component.
*    The highest 8 bits represent the Blue  component.
*/
static GUI_CONST_STORAGE GUI_COLOR _Colorsflolder_name[] = {
  0xCAB172, 0x977100, 0xCDBD83
};

static GUI_CONST_STORAGE GUI_LOGPALETTE _Palflolder_name = {
  3,  // Number of entries
  0,  // No transparency
  &_Colorsflolder_name[0]
};

static GUI_CONST_STORAGE unsigned char _acflolder_name[] = {
  0x55, 0x55, 0x55, 0x55, 0x55, 0x55, 0x40,
  0x55, 0x55, 0x55, 0x55, 0x55, 0x55, 0x40,
  0x55, 0x55, 0x55, 0x55, 0x55, 0x55, 0x40,
  0x55, 0x55, 0x55, 0x52, 0xAA, 0xA8, 0x40,
  0x52, 0xAA, 0xAA, 0x1A, 0xAA, 0xAA, 0x40,
  0x50, 0x00, 0x01, 0x4A, 0xAA, 0xAA, 0x40,
  0x50, 0x00, 0x00, 0x2A, 0xAA, 0xAA, 0x40,
  0x52, 0xAA, 0xAA, 0xAA, 0xAA, 0xAA, 0x40,
  0x50, 0x00, 0x00, 0x00, 0x00, 0x00, 0x40,
  0x50, 0x00, 0x00, 0x00, 0x00, 0x00, 0x40,
  0x50, 0x00, 0x00, 0x00, 0x00, 0x00, 0x40,
  0x50, 0x00, 0x00, 0x00, 0x00, 0x00, 0x40,
  0x50, 0x00, 0x00, 0x00, 0x00, 0x00, 0x40,
  0x50, 0x00, 0x00, 0x00, 0x00, 0x00, 0x40,
  0x50, 0x00, 0x00, 0x00, 0x00, 0x00, 0x40,
  0x50, 0x00, 0x00, 0x00, 0x00, 0x00, 0x40,
  0x50, 0x00, 0x00, 0x00, 0x00, 0x00, 0x40,
  0x50, 0x00, 0x00, 0x00, 0x00, 0x00, 0x40,
  0x50, 0x00, 0x00, 0x00, 0x00, 0x00, 0x40,
  0x50, 0x00, 0x00, 0x00, 0x00, 0x00, 0x40,
  0x50, 0x00, 0x00, 0x00, 0x00, 0x00, 0x40,
  0x50, 0x00, 0x00, 0x00, 0x00, 0x00, 0x40,
  0x55, 0x55, 0x55, 0x55, 0x55, 0x55, 0x40,
  0x55, 0x55, 0x55, 0x55, 0x55, 0x55, 0x40,
  0x55, 0x55, 0x55, 0x55, 0x55, 0x55, 0x40
};

GUI_CONST_STORAGE GUI_BITMAP bmflolder_name = {
  25, // xSize
  25, // ySize
  7, // BytesPerLine
  2, // BitsPerPixel
  _acflolder_name,  // Pointer to picture data (indices)
  &_Palflolder_name   // Pointer to palette
};

/*************************** End of file ****************************/
