/*********************************************************************
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                           www.segger.com                           *
**********************************************************************
*                                                                    *
* C-file generated by                                                *
*                                                                    *
*        Bitmap Converter for emWin V5.30.                           *
*        Compiled Jul  1 2015, 10:49:26                              *
*                                                                    *
*        (c) 1998 - 2015 Segger Microcontroller GmbH & Co. KG        *
*                                                                    *
**********************************************************************
*                                                                    *
* Source file: button_pressed                                        *
* Dimensions:  2 * 2                                                 *
* NumColors:   2                                                     *
*                                                                    *
**********************************************************************
*/

#include <stdlib.h>

#include "GUI.h"

#ifndef GUI_CONST_STORAGE
  #define GUI_CONST_STORAGE const
#endif

//extern GUI_CONST_STORAGE GUI_BITMAP bmbutton_pressed;

/*********************************************************************
*
*       Palette
*
*  Description
*    The following are the entries of the palette table.
*    The entries are stored as a 32-bit values of which 24 bits are
*    actually used according to the following bit mask: 0xBBGGRR
*
*    The lower   8 bits represent the Red   component.
*    The middle  8 bits represent the Green component.
*    The highest 8 bits represent the Blue  component.
*/
static GUI_CONST_STORAGE GUI_COLOR _Colorsbutton_pressed[] = {
  0x000000, 0xFFFFFF
};

static GUI_CONST_STORAGE GUI_LOGPALETTE _Palbutton_pressed = {
  2,  // Number of entries
  0,  // No transparency
  &_Colorsbutton_pressed[0]
};

static GUI_CONST_STORAGE unsigned char _acbutton_pressed[] = {
  ________,
  ________
};

GUI_CONST_STORAGE GUI_BITMAP bmbutton_pressed = {
  2, // xSize
  2, // ySize
  1, // BytesPerLine
  1, // BitsPerPixel
  _acbutton_pressed,  // Pointer to picture data (indices)
  &_Palbutton_pressed   // Pointer to palette
};

/*************************** End of file ****************************/
