/*********************************************************************
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                           www.segger.com                           *
**********************************************************************
*                                                                    *
* C-file generated by                                                *
*                                                                    *
*        Bitmap Converter for emWin V5.30.                           *
*        Compiled Jul  1 2015, 10:49:26                              *
*                                                                    *
*        (c) 1998 - 2015 Segger Microcontroller GmbH & Co. KG        *
*                                                                    *
**********************************************************************
*                                                                    *
* Source file: wifi_status                                           *
* Dimensions:  20 * 20                                               *
* NumColors:   2                                                     *
*                                                                    *
**********************************************************************
*/

#include <stdlib.h>
#include "jack_emwin.h"
#include "GUI.h"

#ifndef GUI_CONST_STORAGE
  #define GUI_CONST_STORAGE const
#endif

extern GUI_CONST_STORAGE GUI_BITMAP bmwifi_status_init;
extern GUI_CONST_STORAGE GUI_BITMAP bmwifi_status_disconnect;
extern GUI_CONST_STORAGE GUI_BITMAP bmwifi_status_connect;
extern GUI_CONST_STORAGE GUI_BITMAP bmwifi_status_timeout;

/*********************************************************************
*
*       Palette
*
*  Description
*    The following are the entries of the palette table.
*    The entries are stored as a 32-bit values of which 24 bits are
*    actually used according to the following bit mask: 0xBBGGRR
*
*    The lower   8 bits represent the Red   component.
*    The middle  8 bits represent the Green component.
*    The highest 8 bits represent the Blue  component.
*/
static GUI_CONST_STORAGE GUI_COLOR _Colorswifi_status_init[] = {
  GUI_LIGHTGRAY, GUI_LIGHTGRAY
};

static GUI_CONST_STORAGE GUI_COLOR _Colorswifi_status_disconnect[] = {
  GUI_RED, GUI_LIGHTGRAY
};

static GUI_CONST_STORAGE GUI_COLOR _Colorswifi_status_connect[] = {
  GUI_BLUE, GUI_LIGHTGRAY
};

static GUI_CONST_STORAGE GUI_COLOR _Colorswifi_status_timeout[] = {
  GUI_YELLOW, GUI_LIGHTGRAY
};

static GUI_CONST_STORAGE GUI_LOGPALETTE _Palwifi_status_init= {
  2,  // Number of entries
  0,  // No transparency
  &_Colorswifi_status_init[0]
};

static GUI_CONST_STORAGE GUI_LOGPALETTE _Palwifi_status_disconnect= {
  2,  // Number of entries
  0,  // No transparency
  &_Colorswifi_status_disconnect[0]
};

static GUI_CONST_STORAGE GUI_LOGPALETTE _Palwifi_status_connect= {
  2,  // Number of entries
  0,  // No transparency
  &_Colorswifi_status_connect[0]
};

static GUI_CONST_STORAGE GUI_LOGPALETTE _Palwifi_status_timeout= {
  2,  // Number of entries
  0,  // No transparency
  &_Colorswifi_status_timeout[0]
};


static GUI_CONST_STORAGE unsigned char _acwifi_status[] = {
  ____XXXX, XXXXXXXX, XXXX____,
  ________, XXXXXXXX, XXXX____,
  ________, __XXXXXX, XXXX____,
  ________, ___XXXXX, XXXX____,
  XXXX____, _____XXX, XXXX____,
  XXXXXXX_, ______XX, XXXX____,
  XXXXXXXX, X______X, XXXX____,
  ____XXXX, XX______, XXXX____,
  _______X, XXX_____, XXXX____,
  ________, XXXX____, _XXX____,
  ________, _XXXX___, __XX____,
  XXXX____, __XXXX__, __XX____,
  XXXXXX__, ___XXX__, ___X____,
  XXXXXXX_, ____XXX_, ___X____,
  XXXXXXXX, ____XXX_, ___X____,
  X____XXX, ____XXX_, ___X____,
  _____XXX, X____XXX, ________,
  _____XXX, X____XXX, ________,
  _____XXX, X____XXX, ________,
  X___XXXX, X____XXX, ________
};

GUI_CONST_STORAGE GUI_BITMAP bmwifi_status_init = {
  20, // xSize
  20, // ySize
  3, // BytesPerLine
  1, // BitsPerPixel
  _acwifi_status,  // Pointer to picture data (indices)
  &_Palwifi_status_init   // Pointer to palette
};

GUI_CONST_STORAGE GUI_BITMAP bmwifi_status_disconnect = {
  20, // xSize
  20, // ySize
  3, // BytesPerLine
  1, // BitsPerPixel
  _acwifi_status,  // Pointer to picture data (indices)
  &_Palwifi_status_disconnect   // Pointer to palette
};

GUI_CONST_STORAGE GUI_BITMAP bmwifi_status_connect = {
  20, // xSize
  20, // ySize
  3, // BytesPerLine
  1, // BitsPerPixel
  _acwifi_status,  // Pointer to picture data (indices)
  &_Palwifi_status_connect   // Pointer to palette
};

GUI_CONST_STORAGE GUI_BITMAP bmwifi_status_timeout = {
  20, // xSize
  20, // ySize
  3, // BytesPerLine
  1, // BitsPerPixel
  _acwifi_status,  // Pointer to picture data (indices)
  &_Palwifi_status_timeout   // Pointer to palette
};

/*************************** End of file ****************************/
