/*********************************************************************
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                           www.segger.com                           *
**********************************************************************
*                                                                    *
* C-file generated by                                                *
*                                                                    *
*        Bitmap Converter for emWin V5.30.                           *
*        Compiled Jul  1 2015, 10:49:26                              *
*                                                                    *
*        (c) 1998 - 2015 Segger Microcontroller GmbH & Co. KG        *
*                                                                    *
**********************************************************************
*                                                                    *
* Source file: manual_celsius                                        *
* Dimensions:  15 * 18                                               *
* NumColors:   3                                                     *
*                                                                    *
**********************************************************************
*/

#include <stdlib.h>

#include "GUI.h"

#ifndef GUI_CONST_STORAGE
  #define GUI_CONST_STORAGE const
#endif

extern GUI_CONST_STORAGE GUI_BITMAP bmmanual_celsius;

/*********************************************************************
*
*       Palette
*
*  Description
*    The following are the entries of the palette table.
*    The entries are stored as a 32-bit values of which 24 bits are
*    actually used according to the following bit mask: 0xBBGGRR
*
*    The lower   8 bits represent the Red   component.
*    The middle  8 bits represent the Green component.
*    The highest 8 bits represent the Blue  component.
*/
static GUI_CONST_STORAGE GUI_COLOR _Colorsmanual_celsius[] = {
  0x9C7300, 0xECE6CF, 0xB69E4A
};

static GUI_CONST_STORAGE GUI_LOGPALETTE _Palmanual_celsius = {
  3,  // Number of entries
  0,  // No transparency
  &_Colorsmanual_celsius[0]
};

static GUI_CONST_STORAGE unsigned char _acmanual_celsius[] = {
  0x00, 0x00, 0x00, 0x00,
  0x00, 0x00, 0x00, 0x00,
  0x00, 0x00, 0x00, 0x00,
  0x15, 0x80, 0x95, 0x54,
  0x59, 0x42, 0x55, 0x54,
  0x62, 0x49, 0x60, 0x00,
  0x99, 0x45, 0x80, 0x00,
  0x26, 0x25, 0x00, 0x00,
  0x00, 0x26, 0x00, 0x00,
  0x00, 0x16, 0x00, 0x00,
  0x00, 0x16, 0x00, 0x00,
  0x00, 0x25, 0x00, 0x00,
  0x00, 0x25, 0x00, 0x00,
  0x00, 0x05, 0x60, 0x00,
  0x00, 0x01, 0x56, 0x94,
  0x00, 0x00, 0x95, 0x54,
  0x00, 0x00, 0x02, 0x80,
  0x00, 0x00, 0x00, 0x00
};

GUI_CONST_STORAGE GUI_BITMAP bmmanual_celsius = {
  15, // xSize
  18, // ySize
  4, // BytesPerLine
  2, // BitsPerPixel
  _acmanual_celsius,  // Pointer to picture data (indices)
  &_Palmanual_celsius   // Pointer to palette
};

/*************************** End of file ****************************/
